const IndexType = {
    BANKNIFTY: "BANKNIFTY",
    FINNIFTY: "FINNIFTY",
    NIFTY50: "NIFTY50",
}
const BANKNIFTY_LOT_SIZE = 30;
const FINNIFTY_LOT_SIZE = 65;
const NIFTY50_LOT_SIZE = 75;

export {
    BANKNIFTY_LOT_SIZE,
    FINNIFTY_LOT_SIZE, IndexType, NIFTY50_LOT_SIZE
};
